# Generated by Django 4.0.3 on 2022-03-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hashtag_remove_post_hashtag_post_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(blank=True, null=True, to='core.hashtag'),
        ),
    ]
