# Generated by Django 4.0.3 on 2022-03-23 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_hashtag_name_hashtag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
