# Generated by Django 4.0.3 on 2022-03-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_hashtag_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
