# Generated by Django 4.0.3 on 2022-03-24 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_alter_post_hashtags_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
