# Generated by Django 4.0.3 on 2022-03-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_hashtag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='user',
        ),
    ]
