# Generated by Django 4.0.3 on 2022-03-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_friend_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaton',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'follow'), ('friend_now', 'friend_now'), ('friend_req', 'friend_req'), ('notification', 'notification')], default='notification', max_length=20),
        ),
    ]
