# Generated by Django 4.0.3 on 2022-03-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_notificaton_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaton',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'follow'), ('friend_now', 'friend_now'), ('friend_request', 'friend_request'), ('notification', 'notification')], default='notification', max_length=20),
        ),
    ]
